name: Deploy JSON to GitHub Pages

on:
  push:
    branches:
      - main  # 触发构建的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取整个历史记录

    - name: Fetch and update JSON
      run: |
        # 安装 cURL
        sudo apt-get update && sudo apt-get install -y curl

        # 从 Formspree 获取数据
        curl -X POST https://formspree.io/f/YOUR_FORMSPREE_FORM -d "name=John%20Doe" -d "email=johndoe@example.com" -d "message=Hello%20from%20Formspree"

        # 假设 Formspree 返回的数据存储在 messages.json
        cat messages.json > public/messages.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
